version: "3.8"

services:
  postgres:
    container_name: ${PROJECT_SLUG}_postgres
    image: dockerhub.timeweb.cloud/postgres:16.0-alpine
    platform: linux/amd64
    restart: unless-stopped
    env_file: postgres.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - internal

  backend:
    container_name: ${PROJECT_SLUG}_backend
    image: registry.git.snpdev.ru/saltpepper/${PROJECT_SLUG}/backend:latest
    restart: unless-stopped
    env_file: backend.env
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - internal
    depends_on:
      - postgres

  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    image: registry.git.snpdev.ru/saltpepper/${PROJECT_SLUG}/frontend:latest
    restart: unless-stopped
    env_file: frontend.env
    networks:
      - internal
    ports:
      - "3000:3000"
    depends_on:
      - backend

  imgproxy:
    container_name: ${PROJECT_SLUG}_imgproxy
    image: dockerhub.timeweb.cloud/darthsim/imgproxy:v3.8.0
    restart: unless-stopped
    env_file: imgproxy.env

    volumes:
      - strapi-uploads:/opt/app/public/uploads:ro
    networks:
      - internal
    ports:
      - "8080:8080"
    depends_on:
      - backend

  meilisearch:
    container_name: ${PROJECT_SLUG}_meilisearch
    image: dockerhub.timeweb.cloud/getmeili/meilisearch:v1.11
    restart: unless-stopped
    env_file: meilisearch.env
    volumes:
      - meilisearch-data:/meili_data
    networks:
      - internal
    ports:
      - "7700:7700"

volumes:
  strapi-data:
    name: ${PROJECT_SLUG}_strapi-data
  strapi-uploads:
    name: ${PROJECT_SLUG}_strapi-uploads
  meilisearch-data:
    name: ${PROJECT_SLUG}_meilisearch-data

networks:
  internal:
    name: ${PROJECT_SLUG}_internal
    driver: bridge